#!/usr/bin/env python

import mailbox, sys
from subprocess import Popen, PIPE

if Popen(["git", "fetch", "origin"]).wait():
	sys.exit(1)

mbox = mailbox.Maildir("~/Mail/vz/criu", factory=mailbox.MaildirMessage)
mlist = {}
for k in mbox.keys():
	m = mbox.get_message(k)
	if 'S' in m.get_flags():
		continue;
	if not m.get('References'):
		mlist[m['message-id']] = [k]

for k in mbox.keys():
	m = mbox.get_message(k)
	if 'S' in m.get_flags():
		continue;
	if m.get('References'):
		print m['References'].split()
		for r in m['References'].split():
			if r in mlist:
				mlist[r].append(k)
				break
	m.add_flag('S')
	mbox[k] = m

for r in mlist:
	print "-----", r
	if Popen(["git", "checkout", "origin/criu-dev"]).wait():
		sys.exit(1)
	Popen(["git", "clean", "-dxf"]).wait()
	mlist[r].sort(lambda a,b: cmp(mbox.get(a)['subject'].split(), mbox.get(b)['subject'].split()))
	i = 0;
	for k in mlist[r]:
		f = mbox.get_file(k)
		devnull = open("/dev/null", "w+")
		m = mbox[k]
		m.add_flag('S')
		p = Popen(["git", "apply", "--stat", "-"], stdin = PIPE, stdout = devnull, stderr = devnull)
		p.stdin.write(f.read())
		p.stdin.close()
		if p.wait() != 0:
			print "Skip\t", m['Subject']
			mbox[k] = m
			continue
		print "Apply\t", m['Subject']
		f = mbox.get_file(k)
		m.add_flag('P')
		p = Popen(["git", "am", "-m", "-"], stdin = PIPE)
		p.stdin.write(f.read())
		p.stdin.close()
		if p.wait() != 0:
			Popen(["git", "am", "--abort"]).wait()
			mbox[k] = m
			break;
		m.add_flag('R')
		mbox[k] = m
		i += 1
	else:
		if i == 0:
			continue
		print "Push\t", k
		if Popen(["git", "branch", k]).wait() != 0:
			continue;
		if Popen(["git", "push", "avagin", k]).wait() != 0:
			continue;
